Upgrade controller-runtime to 0.17.3
open-cluster-management-io/governance-policy-framework-addon pull request #137
Opened 2024-04-29 18:07 UTC by JeffeyL

Changes required to update controller-runtime to 0.17.3

Ref: https://issues.redhat.com/browse/ACM-10835

2024-04-29 19:32 UTC, JustinKuli requested changes

2024-04-29 19:32 UTC, JustinKuli commented on go.mod
> -	google.golang.org/protobuf => google.golang.org/protobuf v1.33.0 // CVE-2024-24786; >=v1.33.0
If I'm reading go.sum correctly, I think we want to keep this one; without this replace clause, we use v1.31.0 which seems like it would be vulnerable

2024-04-30 00:47 UTC, JustinKuli approved these changes
lgtm

2024-04-30 00:55 UTC, merged

2024-04-30 13:22 UTC, JeffeyL commented
Whoops, didn't mean to request another review