Conditionally clean up Gatekeeper Constraints
open-cluster-management-io/governance-policy-framework-addon pull request #43
Opened 2023-03-31 21:16 UTC by dhaiducek

Listing Gatekeeper Constraints was refreshing the discovery API. This adds a global boolean to only attempt cleanup when a Constraint was previously synced successfully.

2023-04-03 10:49 UTC, JustinKuli submitted a review, later dismissed
/hold for @mprahl 

LGTM! It's easier than I would have expected to transition the global back to false, so that's really nice.

2023-04-03 12:51 UTC, mprahl commented on controllers/templatesync/template_sync.go
> +	createdGkConstraint = false
Could you make this a struct member of the reconciler instead?

2023-04-03 12:54 UTC, mprahl commented on controllers/templatesync/template_sync.go
> +				createdGkConstraint = true
It'd be nice to not assume that any cluster scoped policy template is Gatekeeper.

2023-04-03 13:41 UTC, dhaiducek commented
/unhold

2023-04-03 13:53 UTC, mprahl commented on controllers/templatesync/template_sync.go
> +				*r.createdGkConstraint = false
You'll want to explicitly set this to `false` on errors when the CRD doesn't exist error is encountered.

2023-04-04 12:47 UTC, mprahl approved these changes

2023-04-04 12:50 UTC, mprahl commented
/hold for an additional comment

2023-04-04 12:54 UTC, mprahl requested changes
Just one more comment.

2023-04-04 15:10 UTC, dhaiducek commented on controllers/templatesync/template_sync.go
>  		}
Oh yeah, that makes more sense.

2023-04-04 17:03 UTC, mprahl commented
/unhold

2023-04-04 17:09 UTC, merged